import "../../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/app/_components/sidebar";
import Navbar from "@/app/_components/navbar";

const inter = Inter({ subsets: ["latin"] });
// Define Default Axios BaseURL
// axios.defaults.baseURL = process.env.NEXT_PUBLIC_API_URL;
export const metadata: Metadata = {
  title: "CTA Centralized Staff DB - Welcome to Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: string;
}) {
  return (
    <div
      className="page-wrapper"
      id="main-wrapper"
      data-layout="vertical"
      data-navbarbg="skin6"
      data-sidebartype="full"
      data-sidebar-position="fixed"
      data-header-position="fixed"
    >
      {/* Left Sidebar */}
      <Sidebar />
      <div className="body-wrapper">
        <Navbar />
        <div className="container-fluid">{children}</div>
      </div>
    </div>
  );
}
